# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: SpringBootProj-LayeredApp-ShowData
  datasource:
    url: jdbc:mysql://localhost:3306/EmployeeDB
    username: root
    password: Omkar@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-total: 100
      min-idle: 10
    type: org.apache.commons.dbcp2.BasicDataSource
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
